name: release-artifacts
on:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: adoptopenjdk:16-jdk
      options: --user root
    steps:
      - run: apt update && apt install git -y && git --version
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: FabricMC/fabric-action-scripts@v1
        id: changelog
        with:
          context: changelog
          workflow_id: release.yml
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build publish curseforge modrinth --stacktrace
        env:
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}